//GLScopeMac.java
//GUI For Oscilloscope Functions


//Based on (GPL) Java OpenGL examples from
//http://plugins.netbeans.org/PluginPortal/faces/PluginDetailPage.jsp?pluginid=3260


//This program is free software; you can redistribute it and/or
//modify it under the terms of the GNU General Public License as
//published by the Free Software Foundation; either version 3 of the
//License, or (at your option) any later version.
//
//This program is distributed in the hope that it will be useful, but
//WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
//General Public License for more details:
//http://www.gnu.org/licenses/gpl.txt

//Copyright 2009 Brian Satzinger


package scopeduino.display;

import java.awt.Font;
import java.util.*;

import com.sun.opengl.util.Animator;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.opengl.GLCanvas;
import javax.media.opengl.GLCapabilities;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.JTabbedPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import serial.ScopeDAQ;



/**
 *
 * @author cylab
 * @author mbien
 */
public class GLScopeMac extends JFrame {

    static {
        // When using a GLCanvas, we have to set the Popup-Menues to be HeavyWeight,
        // so they display properly on top of the GLCanvas
        JPopupMenu.setDefaultLightWeightPopupEnabled(false);
    }
    
    private Animator animator;
    GLRenderer rend;
    Refresher r;

    int oldx = -1;
    int oldy = -1;

    /** Creates new form MainFrame */
    public GLScopeMac() {
        initComponents();

      
        setTitle("Scopeduino");

        rend = new GLRenderer();

        canvas.addGLEventListener(rend);
        animator = new Animator(canvas);




        // This is a workaround for the GLCanvas not adjusting its size, when the frame is resized.
        canvas.setMinimumSize(new Dimension());         
        
        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                // Run this on another thread than the AWT event queue to
                // make sure the call to Animator.stop() completes before
                // exiting
                new Thread(new Runnable() {

                    public void run() {
                        animator.stop();
                        System.exit(0);
                    }
                }).start();
            }
        });
    }

    @Override
    public void setVisible(boolean show){
        if(!show)
            animator.stop();
        super.setVisible(show);
        if(!show)
            animator.start();

        
        r = new Refresher(canvas);
        r.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new JPanel();
        buttonGroup1 = new ButtonGroup();
        buttonGroup2 = new ButtonGroup();
        buttonGroup3 = new ButtonGroup();
        buttonGroup4 = new ButtonGroup();
        canvas = new GLCanvas(createGLCapabilites());
        jSlider6 = new JSlider();
        jPanel1 = new JPanel();
        jTabbedPane1 = new JTabbedPane();
        ConnectionPanel = new JPanel();
        btnDetectSerial = new JButton();
        scrlSerialPorts = new JScrollPane();
        lstSerialPorts = new JList();
        btnConnect = new JButton();
        DisplayPanel = new JPanel();
        chkGrid = new JCheckBox();
        jLabel2 = new JLabel();
        sldBackground = new JSlider();
        jLabel1 = new JLabel();
        sldTTL = new JSlider();
        jLabel9 = new JLabel();
        sldAlpha = new JSlider();
        jCheckBox1 = new JCheckBox();
        jLabel10 = new JLabel();
        sldLineWidth = new JSlider();
        jLabel4 = new JLabel();
        sldSectionWidth1 = new JSlider();
        sldSectionOffset = new JSlider();
        TriggerPanel = new JPanel();
        sldTriggerLevel = new JSlider();
        jLabel3 = new JLabel();
        jCheckBox2 = new JCheckBox();
        jLabel8 = new JLabel();
        list2 = new java.awt.List();
        Ch1Panel = new JPanel();
        jCheckBox3 = new JCheckBox();
        jLabel5 = new JLabel();
        sldCh1VertScale = new JSlider();
        jLabel6 = new JLabel();
        jSlider5 = new JSlider();
        jLabel7 = new JLabel();
        list1 = new java.awt.List();
        Ch2Panel = new JPanel();
        CursorPanel = new JPanel();
        chkCursorsEnabled = new JCheckBox();
        jLabel11 = new JLabel();
        sldHorizCursor1 = new JSlider();
        sldHorizCursor2 = new JSlider();
        lbldeltaT = new JLabel();
        lblFreq = new JLabel();
        jLabel14 = new JLabel();
        radCh1 = new JRadioButton();
        radCh2 = new JRadioButton();
        sldVertCursor1 = new JSlider();
        sldVertCursor2 = new JSlider();
        lblV1 = new JLabel();
        lblV2 = new JLabel();
        lbldV = new JLabel();
        jPanel2 = new JPanel();
        jLabel12 = new JLabel();
        jSlider1 = new JSlider();

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        canvas.addMouseWheelListener(new MouseWheelListener() {
            public void mouseWheelMoved(MouseWheelEvent evt) {
                canvasMouseWheelMoved(evt);
            }
        });
        canvas.addMouseListener(new MouseAdapter() {
            public void mouseReleased(MouseEvent evt) {
                canvasMouseReleased(evt);
            }
        });
        canvas.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent evt) {
                canvasMouseDragged(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnDetectSerial.setLabel("Detect Serial Ports");
        btnDetectSerial.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                btnDetectSerialMouseClicked(evt);
            }
        });
        btnDetectSerial.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnDetectSerialActionPerformed(evt);
            }
        });

        lstSerialPorts.setModel(new AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrlSerialPorts.setViewportView(lstSerialPorts);

        btnConnect.setText("Connect");
        btnConnect.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                btnConnectMouseClicked(evt);
            }
        });

        GroupLayout ConnectionPanelLayout = new GroupLayout(ConnectionPanel);
        ConnectionPanel.setLayout(ConnectionPanelLayout);
        ConnectionPanelLayout.setHorizontalGroup(
            ConnectionPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(ConnectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConnectionPanelLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(scrlSerialPorts, GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(btnDetectSerial, GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(btnConnect, GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addContainerGap())
        );
        ConnectionPanelLayout.setVerticalGroup(
            ConnectionPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(ConnectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDetectSerial)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(scrlSerialPorts, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(btnConnect)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Connection", ConnectionPanel);

        DisplayPanel.setBorder(BorderFactory.createEtchedBorder());
        DisplayPanel.setLayout(new GridLayout(15, 0));

        chkGrid.setSelected(true);
        chkGrid.setText("Grid");
        chkGrid.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                chkGridActionPerformed(evt);
            }
        });
        DisplayPanel.add(chkGrid);

        jLabel2.setText(" Background:");
        DisplayPanel.add(jLabel2);

        sldBackground.setMajorTickSpacing(100);
        sldBackground.setPaintTicks(true);
        sldBackground.setSnapToTicks(true);
        sldBackground.setValue(0);
        sldBackground.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldBackgroundStateChanged(evt);
            }
        });
        DisplayPanel.add(sldBackground);

        jLabel1.setText(" Time To Live:");
        DisplayPanel.add(jLabel1);

        sldTTL.setMaximum(1024);
        sldTTL.setMinimum(1);
        sldTTL.setValue(127);
        sldTTL.addMouseListener(new MouseAdapter() {
            public void mouseReleased(MouseEvent evt) {
                sldTTLMouseReleased(evt);
            }
        });
        sldTTL.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldTTLStateChanged(evt);
            }
        });
        DisplayPanel.add(sldTTL);

        jLabel9.setText(" Alpha:");
        DisplayPanel.add(jLabel9);

        sldAlpha.setMinimum(5);
        sldAlpha.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldAlphaStateChanged(evt);
            }
        });
        DisplayPanel.add(sldAlpha);

        jCheckBox1.setText("Hard First Trace");
        jCheckBox1.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        DisplayPanel.add(jCheckBox1);

        jLabel10.setText("Line Width");
        DisplayPanel.add(jLabel10);

        sldLineWidth.setMinimum(5);
        sldLineWidth.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldLineWidthStateChanged(evt);
            }
        });
        DisplayPanel.add(sldLineWidth);

        jLabel4.setText("Horizontal Scale:");
        DisplayPanel.add(jLabel4);

        sldSectionWidth1.setMaximum(256);
        sldSectionWidth1.setValue(256);
        sldSectionWidth1.setName("Time To Live"); // NOI18N
        sldSectionWidth1.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldSectionWidth1StateChanged(evt);
            }
        });
        sldSectionWidth1.addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent evt) {
                sldSectionWidth1PropertyChange(evt);
            }
        });
        DisplayPanel.add(sldSectionWidth1);

        sldSectionOffset.setMaximum(256);
        sldSectionOffset.setValue(0);
        sldSectionOffset.setName("Time To Live"); // NOI18N
        sldSectionOffset.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldSectionOffsetStateChanged(evt);
            }
        });
        sldSectionOffset.addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent evt) {
                sldSectionOffsetPropertyChange(evt);
            }
        });
        DisplayPanel.add(sldSectionOffset);

        jTabbedPane1.addTab("Display", DisplayPanel);

        sldTriggerLevel.setMaximum(1024);
        sldTriggerLevel.setMinimum(1);
        sldTriggerLevel.setValue(127);
        sldTriggerLevel.addMouseListener(new MouseAdapter() {
            public void mouseReleased(MouseEvent evt) {
                sldTriggerLevelMouseReleased(evt);
            }
            public void mouseExited(MouseEvent evt) {
                sldTriggerLevelMouseExited(evt);
            }
            public void mouseEntered(MouseEvent evt) {
                sldTriggerLevelMouseEntered(evt);
            }
        });
        sldTriggerLevel.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldTriggerLevelStateChanged(evt);
            }
        });

        jLabel3.setText("Trigger Level");

        jCheckBox2.setText("Trigger Enabled");
        jCheckBox2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Trigger Source");

        GroupLayout TriggerPanelLayout = new GroupLayout(TriggerPanel);
        TriggerPanel.setLayout(TriggerPanelLayout);
        TriggerPanelLayout.setHorizontalGroup(
            TriggerPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(TriggerPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(TriggerPanelLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(sldTriggerLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(TriggerPanelLayout.createParallelGroup(Alignment.TRAILING, false)
                        .addComponent(list2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        TriggerPanelLayout.setVerticalGroup(
            TriggerPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(TriggerPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(sldTriggerLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(list2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trigger", TriggerPanel);

        Ch1Panel.setLayout(new GridLayout(12, 0));

        jCheckBox3.setText("Channel 1 Enable");
        jCheckBox3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        Ch1Panel.add(jCheckBox3);

        jLabel5.setText("Vertical Scale");
        Ch1Panel.add(jLabel5);

        sldCh1VertScale.setMajorTickSpacing(1);
        sldCh1VertScale.setMaximum(3);
        sldCh1VertScale.setMinimum(1);
        sldCh1VertScale.setPaintTicks(true);
        sldCh1VertScale.setSnapToTicks(true);
        sldCh1VertScale.setValue(1);
        sldCh1VertScale.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldCh1VertScaleStateChanged(evt);
            }
        });
        sldCh1VertScale.addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent evt) {
                sldCh1VertScalePropertyChange(evt);
            }
        });
        Ch1Panel.add(sldCh1VertScale);

        jLabel6.setText("Vertical Offset");
        Ch1Panel.add(jLabel6);

        jSlider5.setMaximum(255);
        jSlider5.setMinimum(1);
        jSlider5.setValue(127);
        jSlider5.addMouseListener(new MouseAdapter() {
            public void mouseReleased(MouseEvent evt) {
                jSlider5MouseReleased(evt);
            }
        });
        Ch1Panel.add(jSlider5);

        jLabel7.setText("Color");
        Ch1Panel.add(jLabel7);
        Ch1Panel.add(list1);

        jTabbedPane1.addTab("Ch1", Ch1Panel);

        GroupLayout Ch2PanelLayout = new GroupLayout(Ch2Panel);
        Ch2Panel.setLayout(Ch2PanelLayout);
        Ch2PanelLayout.setHorizontalGroup(
            Ch2PanelLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
        Ch2PanelLayout.setVerticalGroup(
            Ch2PanelLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ch2", Ch2Panel);

        CursorPanel.setLayout(new GridLayout(14, 0));

        chkCursorsEnabled.setFont(new Font("Dialog", 0, 12));
        chkCursorsEnabled.setText("Cursors On");
        chkCursorsEnabled.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                chkCursorsEnabledStateChanged(evt);
            }
        });
        chkCursorsEnabled.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                chkCursorsEnabledActionPerformed(evt);
            }
        });
        CursorPanel.add(chkCursorsEnabled);

        jLabel11.setText("Horizontal Cursors:");
        CursorPanel.add(jLabel11);

        sldHorizCursor1.setMaximum(1024);
        sldHorizCursor1.setValue(0);
        sldHorizCursor1.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldHorizCursor1StateChanged(evt);
            }
        });
        CursorPanel.add(sldHorizCursor1);

        sldHorizCursor2.setMaximum(1024);
        sldHorizCursor2.setValue(0);
        sldHorizCursor2.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldHorizCursor2StateChanged(evt);
            }
        });
        CursorPanel.add(sldHorizCursor2);

        lbldeltaT.setFont(new Font("Dialog", 0, 12));
        lbldeltaT.setText("delta T = ");
        CursorPanel.add(lbldeltaT);

        lblFreq.setFont(new Font("Dialog", 0, 12));
        lblFreq.setText("1 / (delta T) = ");
        CursorPanel.add(lblFreq);

        jLabel14.setText("Vertical Cursors:");
        CursorPanel.add(jLabel14);

        radCh1.setFont(new Font("Dialog", 0, 12));
        radCh1.setSelected(true);
        radCh1.setText("Channel 1");
        radCh1.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                radCh1StateChanged(evt);
            }
        });
        CursorPanel.add(radCh1);

        radCh2.setFont(new Font("Dialog", 0, 12));
        radCh2.setText("Channel 2");
        radCh2.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                radCh2StateChanged(evt);
            }
        });
        radCh2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                radCh2ActionPerformed(evt);
            }
        });
        CursorPanel.add(radCh2);

        sldVertCursor1.setMaximum(1024);
        sldVertCursor1.setValue(0);
        sldVertCursor1.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldVertCursor1StateChanged(evt);
            }
        });
        CursorPanel.add(sldVertCursor1);

        sldVertCursor2.setMaximum(1024);
        sldVertCursor2.setValue(0);
        sldVertCursor2.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldVertCursor2StateChanged(evt);
            }
        });
        CursorPanel.add(sldVertCursor2);

        lblV1.setFont(new Font("Dialog", 0, 12));
        lblV1.setText("V1 =");
        CursorPanel.add(lblV1);

        lblV2.setFont(new Font("Dialog", 0, 12));
        lblV2.setText("V2 =");
        CursorPanel.add(lblV2);

        lbldV.setFont(new Font("Dialog", 0, 12));
        lbldV.setText("dV =");
        CursorPanel.add(lbldV);

        jTabbedPane1.addTab("Cursors", CursorPanel);

        jPanel2.setLayout(new GridLayout(6, 0));

        jLabel12.setText("Frequency");
        jPanel2.add(jLabel12);

        jSlider1.setMaximum(15000);
        jSlider1.setMinimum(50);
        jPanel2.add(jSlider1);

        jTabbedPane1.addTab("tab7", jPanel2);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSlider6, GroupLayout.PREFERRED_SIZE, 0, GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(canvas, GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 287, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jSlider6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(jTabbedPane1, 0, 0, Short.MAX_VALUE)
                            .addComponent(canvas, GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Connection");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

            //rend.rotate = !rend.rotate;


    }//GEN-LAST:event_formMouseClicked

    private void sldBackgroundStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldBackgroundStateChanged
        int color = sldBackground.getValue();

        float colorf =((float) color) / (100.0f);

        ScopeSettings.backb = colorf;
        ScopeSettings.backg = colorf;
        ScopeSettings.backr = colorf;
    }//GEN-LAST:event_sldBackgroundStateChanged

    private void jCheckBox1StateChanged(ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        ScopeSettings.hardFirstTrace = jCheckBox1.isSelected();
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void canvasMouseDragged(MouseEvent evt) {//GEN-FIRST:event_canvasMouseDragged
        // TODO add your handling code here:
        if ((oldx == -1) || (oldy == -1))
        {
            oldx = evt.getX();
            oldy = evt.getY();
            return;
        }

        int dx = evt.getX() - oldx;
        int dy = oldy - evt.getY();


        oldx = evt.getX();
        oldy = evt.getY();

        rend.translate(dx, dy, 0);
    }//GEN-LAST:event_canvasMouseDragged

    private void canvasMouseReleased(MouseEvent evt) {//GEN-FIRST:event_canvasMouseReleased
        //Mouse drag ended
        oldx = -1;
        oldy = -1;
    }//GEN-LAST:event_canvasMouseReleased

    private void canvasMouseWheelMoved(MouseWheelEvent evt) {//GEN-FIRST:event_canvasMouseWheelMoved
        int dz =  -1 * evt.getWheelRotation();

        rend.translate(0, 0, dz);
    }//GEN-LAST:event_canvasMouseWheelMoved

    private void btnDetectSerialActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDetectSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetectSerialActionPerformed

    private void btnDetectSerialMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btnDetectSerialMouseClicked
        Vector<String> ports = rend.arduino.getPorts();

        lstSerialPorts.setListData(ports);

    }//GEN-LAST:event_btnDetectSerialMouseClicked

    private void btnConnectMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseClicked
        String portname = (String)lstSerialPorts.getSelectedValue();
        
        System.out.println(portname);

        try
        {
            rend.arduino.connect(portname);
        }
        catch (Exception e)
        {
            System.err.println("Couldn't Connect: " + e);
        }

        rend.startTraceReader();
       

    }//GEN-LAST:event_btnConnectMouseClicked

    private void formWindowOpened(WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void sldTriggerLevelMouseReleased(MouseEvent evt) {//GEN-FIRST:event_sldTriggerLevelMouseReleased
        int val = sldTriggerLevel.getValue();

        System.out.println("Sample Slider: " + val);

        byte[] command = new byte[2];

        command[0] = 'c';
        command[1] = (byte) val;

        if (rend.reader != null)
        {
            rend.reader.commandQueue.add(command);
        }
    }//GEN-LAST:event_sldTriggerLevelMouseReleased

    private void jCheckBox2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void sldTTLMouseReleased(MouseEvent evt) {//GEN-FIRST:event_sldTTLMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sldTTLMouseReleased

    private void jSlider5MouseReleased(MouseEvent evt) {//GEN-FIRST:event_jSlider5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider5MouseReleased

    private void sldSectionWidth1StateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldSectionWidth1StateChanged
        ScopeSettings.horizontalWindow = sldSectionWidth1.getValue();
    }//GEN-LAST:event_sldSectionWidth1StateChanged

    private void sldSectionWidth1PropertyChange(PropertyChangeEvent evt) {//GEN-FIRST:event_sldSectionWidth1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sldSectionWidth1PropertyChange

    private void sldSectionOffsetStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldSectionOffsetStateChanged
        ScopeSettings.horizontalOffset = sldSectionOffset.getValue();
    }//GEN-LAST:event_sldSectionOffsetStateChanged

    private void sldSectionOffsetPropertyChange(PropertyChangeEvent evt) {//GEN-FIRST:event_sldSectionOffsetPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sldSectionOffsetPropertyChange

    private void sldAlphaStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldAlphaStateChanged
        Trace.alpha = (float) sldAlpha.getValue() / (100.0f);
    }//GEN-LAST:event_sldAlphaStateChanged

    private void sldTTLStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldTTLStateChanged
        Trace.TTL = sldTTL.getValue();
    }//GEN-LAST:event_sldTTLStateChanged

    private void sldLineWidthStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldLineWidthStateChanged
        float lineWidth = (((float) sldLineWidth.getValue()) / 100.0f) * .1f;
        ScopeSettings.lineWidth = lineWidth;
    }//GEN-LAST:event_sldLineWidthStateChanged

    private void chkCursorsEnabledActionPerformed(ActionEvent evt) {//GEN-FIRST:event_chkCursorsEnabledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCursorsEnabledActionPerformed

    private void radCh2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_radCh2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radCh2ActionPerformed

    private void chkCursorsEnabledStateChanged(ChangeEvent evt) {//GEN-FIRST:event_chkCursorsEnabledStateChanged
        if (ScopeSettings.enableCursors != chkCursorsEnabled.isSelected())
        {
            ScopeSettings.enableCursors = chkCursorsEnabled.isSelected();

            recalculateHorizLabels();
            updateCursorColors();
            recalculateVertLabels();
        }
    }//GEN-LAST:event_chkCursorsEnabledStateChanged

    private void sldHorizCursor1StateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldHorizCursor1StateChanged
        float value = sldHorizCursor1.getValue() / 512.0f - 1.0f;

        ScopeSettings.hc1 = value;

        recalculateHorizLabels();
    }//GEN-LAST:event_sldHorizCursor1StateChanged

    private void sldHorizCursor2StateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldHorizCursor2StateChanged
        float value = sldHorizCursor2.getValue() / 512.0f - 1.0f;

        ScopeSettings.hc2 = value;

        recalculateHorizLabels();
    }//GEN-LAST:event_sldHorizCursor2StateChanged

    private void radCh1StateChanged(ChangeEvent evt) {//GEN-FIRST:event_radCh1StateChanged
        radCh2.setSelected(!radCh1.isSelected());

        if (radCh1.isSelected())
        {
            ScopeSettings.vcChannel = 1;
        }
        else
        {
            ScopeSettings.vcChannel = 2;
        }


        updateCursorColors();
        recalculateVertLabels();
    }//GEN-LAST:event_radCh1StateChanged

    private void radCh2StateChanged(ChangeEvent evt) {//GEN-FIRST:event_radCh2StateChanged
        radCh1.setSelected(!radCh2.isSelected());

        if (radCh2.isSelected())
        {
            ScopeSettings.vcChannel = 2;
        }
        else
        {
            ScopeSettings.vcChannel = 1;
        }

        updateCursorColors();
        recalculateVertLabels();
    }//GEN-LAST:event_radCh2StateChanged

    private void sldVertCursor1StateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldVertCursor1StateChanged
        float value = sldVertCursor1.getValue() / 512.0f - 1.0f;

        ScopeSettings.vc1 = value;
        recalculateVertLabels();
    }//GEN-LAST:event_sldVertCursor1StateChanged

    private void updateCursorColors()
    {
        if (ScopeSettings.vcChannel == 1)
        {
            ScopeSettings.vcursorR = (ScopeSettings.ch1R + 1.0f) / 2.0f;
            ScopeSettings.vcursorG = (ScopeSettings.ch1G + 1.0f) / 2.0f;
            ScopeSettings.vcursorB = (ScopeSettings.ch1B + 1.0f) / 2.0f;
        }
        else if (ScopeSettings.vcChannel == 2)
        {
            ScopeSettings.vcursorR = (ScopeSettings.ch2R + 1.0f) / 2.0f;
            ScopeSettings.vcursorG = (ScopeSettings.ch2G + 1.0f) / 2.0f;
            ScopeSettings.vcursorB = (ScopeSettings.ch2B + 1.0f) / 2.0f;
        }
        else
        {
            ScopeSettings.vcursorR = 1.0f;
            ScopeSettings.vcursorG = 1.0f;
            ScopeSettings.vcursorB = 1.0f;
        }
    }

    private void recalculateHorizLabels()
    {
        if (ScopeSettings.enableCursors == false)
        {
            lbldeltaT.setText("delta T = ");
            lblFreq.setText("1 / (delta T) = ");
            return;
        }

        int sampleWindow = ScopeSettings.horizontalWindow;
        float samplePeriod = ScopeSettings.samplePeriod;

        //amount of time represented by the entire graph
        float screenPeriod = sampleWindow * samplePeriod;

        //fraction of the screen taken up by the 2 cursors
        float screenFrac = Math.abs(ScopeSettings.hc2 - ScopeSettings.hc1) / 2;
        //the /2 is because the screen goes from -1 to 1, total width of 2 units

        float dT = screenPeriod * screenFrac;
        float freq = 1 / dT;

        lbldeltaT.setText("delta T = " + (dT * 1000.0f) + " ms");
        lblFreq.setText("1 / (delta T) = " + freq + " Hz");

    }

    private void recalculateVertLabels()
    {
        if (ScopeSettings.enableCursors == false)
        {
            lblV1.setText("V1 =");
            lblV2.setText("V2 =");
            lbldV.setText("dV =");

            return;
        }

        float min = 0.0f;
        float max = 5.0f;

        if (ScopeSettings.vcChannel == 1)
        {
            min = ScopeSettings.ch1MinV;
            max = ScopeSettings.ch1MaxV;
        }
        else if (ScopeSettings.vcChannel == 2)
        {
            min = ScopeSettings.ch2MinV;
            max = ScopeSettings.ch2MaxV;
        }

        //Map the vertical location from [-1,1] to [0,1]
        float cursor1pos = (ScopeSettings.vc1 + 1.0f) / 2.0f;
        float cursor2pos = (ScopeSettings.vc2 + 1.0f) / 2.0f;

        float v1 = (max - min) * cursor1pos + min;
        float v2 = (max - min) * cursor2pos + min;

        lblV1.setText("V1 = " + v1 + " V");
        lblV2.setText("V2 = " + v2 + " V");
        lbldV.setText("dV = " + Math.abs(v2 - v1) + " V");


    }

    private void sldVertCursor2StateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldVertCursor2StateChanged
        float val = sldVertCursor2.getValue() / 512.0f - 1.0f;

        ScopeSettings.vc2 = val;
        recalculateVertLabels();
    }//GEN-LAST:event_sldVertCursor2StateChanged

    private void sldCh1VertScaleStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldCh1VertScaleStateChanged
        int val = sldCh1VertScale.getValue();
        
        //send arduino command
        byte[] command = new byte[2];
         //channel 1 (a) scale command

        command[0] = 'a';

        if (val == 1)
        {
            command[1] = '0';
        }
        else if (val == 2)
        {
            command[1] = '1';
        }
        else
        {
            command[1] = '2';
        }


        System.out.println("Channel 1 uses : " + command[1]);

        if (rend.reader != null)
        {
            rend.reader.commandQueue.add(command);
        }


        //update display info
        if (val == 1)
        {
            ScopeSettings.ch1MinV = 0.0f;
            ScopeSettings.ch1MaxV = 5.0f;
        }
        else if (val == 2)
        {
            ScopeSettings.ch1MinV = -5.0f;
            ScopeSettings.ch1MaxV = 5.0f;
        }
        else if (val == 3)
        {
            ScopeSettings.ch1MinV = -10.0f;
            ScopeSettings.ch1MaxV = 8.438f;
        }
        else
        {
            //default
            ScopeSettings.ch1MinV = 0.0f;
            ScopeSettings.ch1MaxV = 5.0f;
        }

        recalculateVertLabels();
    }//GEN-LAST:event_sldCh1VertScaleStateChanged

    private void sldTriggerLevelMouseEntered(MouseEvent evt) {//GEN-FIRST:event_sldTriggerLevelMouseEntered
        System.out.println("Entered");
        ScopeSettings.enableTriggerIndicator = true;
    }//GEN-LAST:event_sldTriggerLevelMouseEntered

    private void sldTriggerLevelMouseExited(MouseEvent evt) {//GEN-FIRST:event_sldTriggerLevelMouseExited
        System.out.println("Left");
        ScopeSettings.enableTriggerIndicator = false;
    }//GEN-LAST:event_sldTriggerLevelMouseExited

    private void sldTriggerLevelStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldTriggerLevelStateChanged
       int val = sldTriggerLevel.getValue();

       ScopeSettings.triggerIndicator = val / 512.0f - 1.0f;
    }//GEN-LAST:event_sldTriggerLevelStateChanged

    private void chkGridActionPerformed(ActionEvent evt) {//GEN-FIRST:event_chkGridActionPerformed
        ScopeSettings.grid = chkGrid.isSelected();
    }//GEN-LAST:event_chkGridActionPerformed

    private void sldCh1VertScalePropertyChange(PropertyChangeEvent evt) {//GEN-FIRST:event_sldCh1VertScalePropertyChange
        System.out.println("PROPERTY CHANGE");
    }//GEN-LAST:event_sldCh1VertScalePropertyChange

    /**
     * Called from within initComponents().
     * hint: to customize the generated code choose 'Customize Code' in the contextmenu
     * of the selected UI Component you wish to cutomize in design mode.
     * @return Returns customized GLCapabilities.
     */
    private GLCapabilities createGLCapabilites() {
        
        GLCapabilities capabilities = new GLCapabilities();
        capabilities.setHardwareAccelerated(true);

        // try to enable 2x anti aliasing - should be supported on most hardware
        //capabilities.setNumSamples(2);
        //capabilities.setSampleBuffers(true);
        
        return capabilities;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        // Run this in the AWT event thread to prevent deadlocks and race conditions
        EventQueue.invokeLater(new Runnable() {
            public void run() {

                // switch to system l&f for native font rendering etc.
                try{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }catch(Exception ex) {
                    Logger.getLogger(getClass().getName()).log(Level.INFO, "can not enable system look and feel", ex);
                }

                GLScopeMac frame = new GLScopeMac();
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel Ch1Panel;
    private JPanel Ch2Panel;
    private JPanel ConnectionPanel;
    private JPanel CursorPanel;
    private JPanel DisplayPanel;
    private JPanel TriggerPanel;
    private JButton btnConnect;
    private JButton btnDetectSerial;
    private ButtonGroup buttonGroup1;
    private ButtonGroup buttonGroup2;
    private ButtonGroup buttonGroup3;
    private ButtonGroup buttonGroup4;
    private GLCanvas canvas;
    private JCheckBox chkCursorsEnabled;
    private JCheckBox chkGrid;
    private JCheckBox jCheckBox1;
    private JCheckBox jCheckBox2;
    private JCheckBox jCheckBox3;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel14;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel4;
    private JSlider jSlider1;
    private JSlider jSlider5;
    private JSlider jSlider6;
    private JTabbedPane jTabbedPane1;
    private JLabel lblFreq;
    private JLabel lblV1;
    private JLabel lblV2;
    private JLabel lbldV;
    private JLabel lbldeltaT;
    private java.awt.List list1;
    private java.awt.List list2;
    private JList lstSerialPorts;
    private JRadioButton radCh1;
    private JRadioButton radCh2;
    private JScrollPane scrlSerialPorts;
    private JSlider sldAlpha;
    private JSlider sldBackground;
    private JSlider sldCh1VertScale;
    private JSlider sldHorizCursor1;
    private JSlider sldHorizCursor2;
    private JSlider sldLineWidth;
    private JSlider sldSectionOffset;
    private JSlider sldSectionWidth1;
    private JSlider sldTTL;
    private JSlider sldTriggerLevel;
    private JSlider sldVertCursor1;
    private JSlider sldVertCursor2;
    // End of variables declaration//GEN-END:variables

}
